blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Features and ideas
    url: https://github.com/umbraco/Umbraco.UI/discussions/new?category=ideas
    about: Start a new discussion when you have ideas or feature requests, eventually discussions can turn into plans.
  - name: â“ Support Question
    url: https://forum.umbraco.com
    about: This issue tracker is NOT meant for support questions. If you have a question, please join us on the forum.
