blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Features and ideas
    url: https://github.com/umbraco/Umbraco.UI/discussions/new?category=ideas
    about: Start a new discussion when you have ideas or feature requests, eventually discussions can turn into plans.
  - name: â‰ï¸ Support Question
    url: https://our.umbraco.com
    about: This issue tracker is NOT meant for support questions. If you have a question, please join us on the forum.
  - name: ğŸ” Security Issue
    url: https://umbraco.com/about-us/trust-center/security-and-umbraco/how-to-report-a-vulnerability-in-umbraco/
    about: Learn more on how to report security issues.
